name: Deploy React App

on:
  pull_request:
    branches: [ main ] # Adjust this to your main branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x' # Use the appropriate Node.js version for your project

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Run test
        run: npm run test

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
         github_token: ${{ secrets.COMP3104_GITHUB_TOKEN }}
         publish_dir: ./build